//
// This file was generated by Catalyst's C# compiler at 17/05/2025 20:08:06.
// It is recommended not to modify this file. Modify the source spec file instead.
//

using Microsoft.AspNetCore.Mvc;

namespace Lactose.Economy.Items;

[ApiController]
[Route("items")]
public abstract class ItemsControllerBase : ControllerBase
{
    [HttpPost("query", Name = "ItemsQuery")]
    public abstract Task<ActionResult<Lactose.Economy.Items.QueryItemsResponse>> Query(Lactose.Economy.Items.QueryItemsRequest request);

    [HttpPost("get", Name = "ItemsGet")]
    public abstract Task<ActionResult<Lactose.Economy.Items.GetItemsResponse>> Get(Lactose.Economy.Items.GetItemsRequest request);

    [HttpPost("create", Name = "ItemsCreate")]
    public abstract Task<ActionResult<Lactose.Economy.Items.GetItemResponse>> Create(Lactose.Economy.Items.CreateItemRequest request);

    [HttpPost("update", Name = "ItemsUpdate")]
    public abstract Task<ActionResult<Lactose.Economy.Items.GetItemResponse>> Update(Lactose.Economy.Items.UpdateItemRequest request);

    [HttpPost("delete", Name = "ItemsDelete")]
    public abstract Task<ActionResult<Lactose.Economy.Items.DeleteItemsResponse>> Delete(Lactose.Economy.Items.DeleteItemsRequest request);
}
