//
// This file was generated by Catalyst's C# compiler at 17/05/2025 20:08:06.
// It is recommended not to modify this file. Modify the source spec file instead.
//

using Microsoft.AspNetCore.Mvc;

namespace Lactose.Economy.ShopItems;

[ApiController]
[Route("shopItems")]
public abstract class ShopItemsControllerBase : ControllerBase
{
    [HttpPost("get", Name = "ShopItemsGet")]
    public abstract Task<ActionResult<Lactose.Economy.ShopItems.GetShopItemsResponse>> Get(Lactose.Economy.ShopItems.GetShopItemsRequest request);

    [HttpPost("getUserShop", Name = "ShopItemsGetUserShop")]
    public abstract Task<ActionResult<Lactose.Economy.ShopItems.GetShopItemsResponse>> GetUserShop(Lactose.Economy.ShopItems.GetShopItemsForUserRequest request);

    [HttpPost("updateUserShop", Name = "ShopItemsUpdateUserShop")]
    public abstract Task<ActionResult<Lactose.Economy.ShopItems.UpdateUserShopItemsResponse>> UpdateUserShop(Lactose.Economy.ShopItems.UpdateUserShopItemsRequest request);

    [HttpPost("deleteUserShop", Name = "ShopItemsDeleteUserShop")]
    public abstract Task<ActionResult<Lactose.Economy.ShopItems.DeleteUserShopResponse>> DeleteUserShop(Lactose.Economy.ShopItems.DeleteUserShopRequest request);

    [HttpPost("trade", Name = "ShopItemsTrade")]
    public abstract Task<ActionResult<Lactose.Economy.ShopItems.TradeShopItemResponse>> Trade(Lactose.Economy.ShopItems.TradeShopItemRequest request);
}
