//
// This file was generated by Catalyst's C# compiler at 17/05/2025 20:08:06.
// It is recommended not to modify this file. Modify the source spec file instead.
//

using Microsoft.AspNetCore.Mvc;

namespace Lactose.Economy.Transactions;

[ApiController]
[Route("transactions")]
public abstract class TransactionsControllerBase : ControllerBase
{
    [HttpPost("query", Name = "TransactionsQuery")]
    public abstract Task<ActionResult<Lactose.Economy.Transactions.QueryTransactionsResponse>> Query(Lactose.Economy.Transactions.QueryTransactionsRequest request);

    [HttpPost("get", Name = "TransactionsGet")]
    public abstract Task<ActionResult<Lactose.Economy.Transactions.GetTransactionResponse>> Get(Lactose.Economy.Transactions.GetTransactionRequest request);

    [HttpPost("trade", Name = "TransactionsTrade")]
    public abstract Task<ActionResult<Lactose.Economy.Transactions.TradeResponse>> Trade(Lactose.Economy.Transactions.TradeRequest request);
}
