//
// This file was generated by Catalyst's C# compiler at 17/05/2025 20:08:06.
// It is recommended not to modify this file. Modify the source spec file instead.
//

using Microsoft.AspNetCore.Mvc;

namespace Lactose.Economy.UserItems;

[ApiController]
[Route("userItems")]
public abstract class UserItemsControllerBase : ControllerBase
{
    [HttpPost("query", Name = "UserItemsQuery")]
    public abstract Task<ActionResult<Lactose.Economy.UserItems.QueryUserItemsResponse>> Query(Lactose.Economy.UserItems.QueryUserItemsRequest request);

    [HttpPost("get", Name = "UserItemsGet")]
    public abstract Task<ActionResult<Lactose.Economy.UserItems.GetUserItemsResponse>> Get(Lactose.Economy.UserItems.GetUserItemsRequest request);

    [HttpPost("createVendor", Name = "UserItemsCreateVendor")]
    public abstract Task<ActionResult<Lactose.Economy.UserItems.CreateVendorResponse>> CreateVendor(Lactose.Economy.UserItems.CreateVendorRequest request);
}
