---
apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-config
  namespace: lactose
data:
  nginx.conf: |
      events {
        worker_connections 16;
      }

      http {
        server {
            listen 80;
            root /usr/share/nginx/html;
            index index.html;

            sub_filter '__POD_NAME__' '$hostname';
            sub_filter_once off;

            add_header X-Pod-Name '$hostname';

            location / {
                try_files $uri $uri/ =404;
            }
        }
      }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Lactose Connected!</title>
        <style>
            body {
                font-family: 'Inter', sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                margin: 0;
                background-color: #f0f4f8;
                color: #333;
                text-align: center;
            }
            .container {
                background-color: #ffffff;
                padding: 40px 60px;
                border-radius: 15px;
                box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
                max-width: 600px;
                width: 90%;
            }
            h1 {
                color: #2c3e50;
                font-size: 2.5em;
                margin-bottom: 20px;
            }
            p {
                font-size: 1.2em;
                line-height: 1.6;
                color: #555;
            }
            .highlight {
                color: #3498db;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>You have reached Lactose.</h1>
            <p>You are successfully connected to the <span class="highlight">Lactose</span> service via Kubernetes on Pod <span class="highlight">__POD_NAME__</span>.</p>
            <p>You shouldn't really be here though.</p>
        </div>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: lactose
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: landing-html
          mountPath: /usr/share/nginx/html/
          readOnly: true
        - name: landing-nginx-config
          mountPath: /etc/nginx/
          readOnly: true
        resources:
          requests:
            memory: 16Mi
            cpu: 50m
          limits:
            memory: 32Mi
            cpu: 100m
      volumes:
      - name: landing-html
        configMap:
          name: landing-config
          items:
          - key: index.html
            path: index.html
      - name: landing-nginx-config
        configMap:
          name: landing-config
          items:
          - key: nginx.conf
            path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: landing-service
  namespace: lactose
spec:
  selector:
    app: landing
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: landing-ingressroute
  namespace: lactose
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`lactose2.mookrata.ovh`) && Path(`/`)
    kind: Rule
    services:
    - name: landing-service
      port: 80
  - match: Host(`localhost`)
    kind: Rule
    services:
    - name: landing-service
      port: 80
  tls:
    certResolver: external.issuer
    secretName: lactose.mookrata.ovh.tls