# Place this file, for example, in: /var/lib/rancher/k3s/server/manifests/
# Or apply with: kubectl apply -f traefik.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |- 
    global:
      sendAnonymousUsage: false
    log:
      level: debug
    api:
      insecure: true
