//
// This file was generated by Catalyst's C# compiler at 02/05/2025 17:12:38.
// It is recommended not to modify this file. Modify the source spec file instead.
//

using Microsoft.AspNetCore.Mvc;

namespace Lactose.Tasks;

[ApiController]
[Route("tasks")]
public abstract class TasksControllerBase : ControllerBase
{
    [HttpPost("query", Name = "TasksQuery")]
    public abstract Task<ActionResult<Lactose.Tasks.Dtos.QueryTasksResponse>> Query(Lactose.Tasks.Dtos.QueryTasksRequest request);

    [HttpPost("get", Name = "TasksGet")]
    public abstract Task<ActionResult<Lactose.Tasks.Dtos.GetTasksResponse>> Get(Lactose.Tasks.Dtos.GetTasksRequest request);

    [HttpPost("create", Name = "TasksCreate")]
    public abstract Task<ActionResult<Lactose.Tasks.Dtos.GetTaskResponse>> Create(Lactose.Tasks.Dtos.CreateTaskRequest request);

    [HttpPost("delete", Name = "TasksDelete")]
    public abstract Task<ActionResult<Lactose.Tasks.Dtos.DeleteTasksResponse>> Delete(Lactose.Tasks.Dtos.DeleteTasksRequest request);
}
