//
// This file was generated by Catalyst's C# compiler at 02/05/2025 17:12:38.
// It is recommended not to modify this file. Modify the source spec file instead.
//

using Microsoft.AspNetCore.Mvc;

namespace Lactose.Tasks;

[ApiController]
[Route("userTasks")]
public abstract class UserTasksControllerBase : ControllerBase
{
    [HttpPost("query", Name = "UserTasksQuery")]
    public abstract Task<ActionResult<Lactose.Tasks.Dtos.QueryUserTasksResponse>> Query(Lactose.Tasks.Dtos.QueryUserTasksRequest request);

    [HttpPost("get", Name = "UserTasksGet")]
    public abstract Task<ActionResult<Lactose.Tasks.Dtos.GetUserTasksResponse>> Get(Lactose.Tasks.Dtos.GetUserTasksRequest request);
    
    [HttpPost("getById", Name = "UserTasksGetById")]
    public abstract Task<ActionResult<Lactose.Tasks.Dtos.GetUserTasksResponse>> GetById(Lactose.Tasks.Dtos.GetUserTasksFromTaskIdRequest request);
}
