apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: external.issuer
spec:
  acme:
    email: info@mookrata.ovh
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt.private.key
    solvers:
    - dns01:
        cloudflare:
          email: info@mookrata.ovh
          apiTokenSecretRef:
            name: secret.cf.dns.token
            key: value
      selector:
        dnsZones:
        - lactose.mookrata.ovh
        - lactose2.mookrata.ovh

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lactose.mookrata.ovh.tls
  namespace: lactose
spec:
  secretName: lactose.mookrata.ovh.tls
  issuerRef:
    name: external.issuer
    kind: ClusterIssuer
  commonName: lactose2.mookrata.ovh
  dnsNames:
  - lactose.mookrata.ovh
  - lactose2.mookrata.ovh