apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal.root.issuer
  namespace: lactose
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal.root
  namespace: lactose
spec:
  isCA: true
  subject:
    organizations: 
    - Mookrata
    - dynamiquel
  secretName: internal.root.tls
  commonName: Lactose Internal Root CA
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: internal.root.issuer
