//
// This file was generated by Catalyst's C# compiler at 17/05/2025 20:08:06.
// It is recommended not to modify this file. Modify the source spec file instead.
//

using System.Collections.Generic;

namespace Lactose.Economy.ShopItems;

public record ShopItemDto
{
    public required string Id { get; set; }

    public required string UserId { get; set; }

    public required string ItemId { get; set; }

    public required string TransactionType { get; set; }

    public required List<Lactose.Economy.UserItems.UserItem> TransactionItems { get; set; }
    public int Quantity { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static ShopItemDto? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<ShopItemDto>(bytes);
    }
}

public record NewShopItemDto
{
    public required string ItemId { get; set; }

    public required string TransactionType { get; set; }

    public required List<Lactose.Economy.UserItems.UserItem> TransactionItems { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static NewShopItemDto? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<NewShopItemDto>(bytes);
    }
}

public record GetShopItemsRequest
{
    public required List<string> ShopItemIds { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static GetShopItemsRequest? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<GetShopItemsRequest>(bytes);
    }
}

public record GetShopItemsResponse
{
    public required List<Lactose.Economy.ShopItems.ShopItemDto> ShopItems { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static GetShopItemsResponse? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<GetShopItemsResponse>(bytes);
    }
}

public record GetShopItemsForUserRequest
{
    public required string UserId { get; set; }

    public bool RetrieveUserQuantity { get; set; } = false;

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static GetShopItemsForUserRequest? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<GetShopItemsForUserRequest>(bytes);
    }
}

public record UpdateUserShopItemsRequest
{
    public required string UserId { get; set; }

    public List<Lactose.Economy.ShopItems.ShopItemDto>? NewItems { get; set; }

    public List<string>? ItemsToRemove { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static UpdateUserShopItemsRequest? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<UpdateUserShopItemsRequest>(bytes);
    }
}

public record UpdateUserShopItemsResponse
{
    public required List<string> AddedItems { get; set; }

    public required List<string> RemovedItems { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static UpdateUserShopItemsResponse? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<UpdateUserShopItemsResponse>(bytes);
    }
}

public record DeleteUserShopRequest
{
    public required string UserId { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static DeleteUserShopRequest? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<DeleteUserShopRequest>(bytes);
    }
}

public record DeleteUserShopResponse
{

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static DeleteUserShopResponse? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<DeleteUserShopResponse>(bytes);
    }
}

public record TradeShopItemRequest
{
    public required string UserId { get; set; }

    public required string ShopItemId { get; set; }

    public int Quantity { get; set; } = 1;

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static TradeShopItemRequest? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<TradeShopItemRequest>(bytes);
    }
}

public record TradeShopItemResponse
{
    public required string Reason { get; set; }

    public byte[] ToBytes()
    {
        return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(this);
    }

    public static TradeShopItemResponse? FromBytes(ReadOnlySpan<byte> bytes)
    {
        return System.Text.Json.JsonSerializer.Deserialize<TradeShopItemResponse>(bytes);
    }
}
